version: "3.9"

services:
  backend:
    build:
      context: backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"

  database:
    image: postgres:16-alpine3.19
    container_name: db
    restart: unless-stopped
    ports:
      - "5430:5432"
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_NAME:-tunalice}
      POSTGRES_USER: ${DB_USERNAME:-tunalice}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-tunalice}
    volumes:
      - ./database:/docker-entrypoint-initdb.d/